Fix versett-scripts test command to run only on PR, and more dynamic fetching of commit message (#299)
versett/versett-scripts pull request #46
Opened 2019-05-30 17:29 UTC by tamv

Closes versett/versett-boilerplate/issues/299

**Pull Request summary**
Update versett script test to be more dynamic on validating the pr commit messages;
now it will only run when there a pr_url provide (just a simple check, if you want to test this out pass anything into the PR_URL via command line

`PR_URL="test" versett-script test`

**Additional changes**
Update the CircleCI to inject the PR_URL by default

**Checklist**

- [x] I have added a meaningful title to my PR
- [x] The issue number is included in my PR title
- [x] I have branched out of the latest `master` branch
- [x] I have run `yarn test` in my local development environment
- [x] I have tested this PR
- [x] I have made at least one semantic commit to my PR
- [x] I have connected this pull request with an existing issue on Zenhub

2019-05-31 16:07 UTC, ardalann commented on .circleci/config.yml
> +          command: PR_URL=$CIRCLE_PULL_REQUEST yarn test:ci
We should document this env var in README

2019-05-31 16:07 UTC, ardalann commented on bin/commands/test.js
> +      error(`no revision found in this pull request ${process.env.PR_URL}`);
where does the number 2 come from?

2019-05-31 16:10 UTC, mGolestan requested changes

2019-05-31 16:10 UTC, mGolestan commented on bin/commands/test.js
> +  if (process.env.PR_URL) {
I think it doesn't seem to be right to return an error about unconventional commit message, if the `PR_URL` has not passed to the script.
i would prefer
```js
if (!process.env.PR_URL) {
    error("Can't find the PR's url");
    return "error";
}
```

2019-05-31 16:10 UTC, mGolestan commented on bin/commands/test.js
> +    if (commitMessages.length === 0) {
i think we don't need this `if`, because the next function `getFormattedCommitsCount` will fail the test if there is no comments in the PR as well
Also github, itself won't allow to open a PR for a branch which doesn't have any commits

2019-05-31 20:19 UTC, tamv commented on bin/commands/test.js
> +  if (process.env.PR_URL) {
@here, this going to be run on a non PR review branch as well ("when merging into developmnet") or "master" so we need that check here so we don't run this when there no actual change.

2019-05-31 20:22 UTC, tamv reviewed
I have update my comment left by @mGolestan and @ardalann

2019-05-31 20:22 UTC, tamv commented on .circleci/config.yml
> +          command: PR_URL=$CIRCLE_PULL_REQUEST yarn test:ci
will update

2019-06-07 15:14 UTC, mGolestan submitted a review, later dismissed
💯

2019-06-11 19:02 UTC, ardalann requested changes

2019-06-11 19:02 UTC, ardalann commented on bin/commands/test.js
> +const MAX_NO_OF_REV = 2;
Isn't this referring to the maximum number of commits? what is "rev"? I thought it stands for reverse

2019-06-11 19:02 UTC, ardalann commented on README.md
> +5. Append `versett-scripts test` to your CI test script and the ci configuration:
This makes it sounds like we need to add this command in 2 places. How about this?
```suggestion
5. Append `versett-scripts test` to your CI test script:
```

2019-06-11 19:02 UTC, ardalann commented on README.md
> +```yml
I just noticed `PR_URL` is only used as a boolean. We can change it to `IS_PULL_REQUEST` to reflect that. Or even better... change the command to `test-pull-request`, get rid of this env var, and add an `if` around it in the consumer CI config. I think I would prefer that.

2019-06-11 19:06 UTC, tamv commented on README.md
> +5. Append `versett-scripts test` to your CI test script and the ci configuration:
@ardalann -> do you want to revert this?

2019-06-17 21:26 UTC, ardalann commented on README.md
> +5. Append `versett-scripts test` to your CI test script and the ci configuration:
That is my suggestion, yes

2019-06-24 21:57 UTC, tamv commented on README.md
> +```yml
Update

2019-06-24 21:57 UTC, tamv commented on bin/commands/test.js
> +const MAX_NO_OF_REV = 2;
Update

2022-05-03 17:06 UTC, closed without merging